log4j:
    appender:
        info: org.apache.log4j.DailyRollingFileAppender
        info.File: '/logs/test.log '
        info.Threshold: 'info   '
        info.layout.ConversionPattern: '%d{yyyy-MM-dd-HH-mm} [%t] [%c] [%p] - %m%n  '
    rootCategory: ALL,info
mybatis:
    mapper-locations: classpath*:**.*Mapper.xml
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        maxActive: 20
        maxWait: 60000
        minIdle: 5
        password: root
        type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
        url: jdbc:mysql://localhost:3306/plover?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
